# ==============================================================
# FAULTSTREAM - CI/CD
# ==============================================================
# CI NEDIR?
# Bizim yazdığımız kodun otomatik olarak derlenip test edilmesidir
# CD NEDIR?
# CI adımından başarı ile geçen kodun otomatik olarak sunuculara gönderilmesidir
# ==============================================================

name: FaultStream CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
